### ISSUE TITLE
ERROR in ./src/app/nouislider.jsx

### ISSUE THREAD

**Issue by wesselhuising** [jwkvam/bowtie#102]
ERROR in ./src/app/nouislider.jsx
Module not found: Error: Cannot resolve module 'nouislider/src/nouislider.css' in /Users/wesselhuising/Documents/triplea/bowtie/test/build/src/app
 @ ./src/app/nouislider.jsx 15:0-40

Using a virtualenv, followed the documentation about installing and setting up a bowtie app. Tried a lot, but can't figure out how to make the npm use the compiler of less to create a css. This happens while building the example app in the quickstart of the documentation.

Any thoughts?

**Comment by jwkvam** [comment]
Thanks for the reporting this. The correct path is 'nouislider/distribute/nouislider.css' which is defined in `nouislider.jsx`. I'm fixing that right now. Sorry about your lost time. I'm working on a fix now. I should have it out later today.

**Comment by jwkvam** [comment]
This should be fixed in v0.2.5 with #103, please reopen if the problem persists.
