### ISSUE TITLE
What can Schedule do?

### ISSUE THREAD

**Issue by rsm5139** [jwkvam/bowtie#119]
Hi, I'm trying to use Schedule, but it doesn't seem to do anything. I had it call a function to create a plot, but that didn't work. Then I tried having it just print('hello'), but still nothing. I would like to add a timer to the app and I figured Schedule would help, but maybe not.

**Comment by jwkvam** [comment]
@rsm5139 Could you set `debug = False` and retry?

**Comment by jwkvam** [comment]
It also seems I can get the scheduler to work by changing this line in `server.py` from
```
    socketio.run(app, host=host, port=port)
```
to this.
```
    socketio.run(app, host=host, port=port, use_reloader=False)
```
I still want to find a better long-term fix but I hope these workarounds will help you in the short-term.

**Comment by rsm5139** [comment]
I will try that out, thank you.

**Comment by rsm5139** [comment]
I tried adding `socketio.run(app, host=host, port=port, use_reloader=False)` to `server.py`, and that worked. I can even update plots like this! Let's see if I can somehow use this to make a countdown timer.
