### ISSUE TITLE
make widgets with minimum size?

### ISSUE THREAD

**Issue by dswah** [jwkvam/bowtie#20]
I'm working on a dashboard where i'd like to stack 3 widgets, but on my screen they render with very small heights... is there a way to forece them to occupy a minimum height?

![image](https://cloud.githubusercontent.com/assets/11619412/18406768/49d1bd08-76b6-11e6-91b8-7112e5b77f73.png)

**Comment by jwkvam** [comment]
Right now, no. I would like to support this however, this is related to #16.

**Comment by jwkvam** [comment]
I think I can fix this by just specifying min-height and min-width in a few places, shouldn't be much further out.

**Comment by jwkvam** [comment]
fixed in #82
