### ISSUE TITLE
Compare against similar projects 

### ISSUE THREAD

**Issue by jwkvam** [jwkvam/bowtie#6]
- [ ] gleam
- [ ] pyxley
- [ ] [dashboards](https://github.com/plotly/dashboards)
- [ ] [spyre](https://github.com/adamhajari/spyre)

**Comment by b11z** [comment]
Hi, I just learned of bowtie and it looks amazing --  spyre or pyxley aren't nearly as polished in my experience.

One alternative worth mentioning is the (nascent) jupyter dashboards server. Their model is, you deploy an .ipynb to a server, which renders the notebook fresh on each page load, hides all the code blocks and lays out the cells nicely. It's backed by a live jupyter kernel, which means you can build interactivity using ipywidgets. It's also nice in that it enables a development workflow where you test in the notebook before deploying to the dash server. One big drawback is that .ipynbs are hard for devs to collaborate on (diff/merge). Also, there are gaps between what works in the jupyter notebook and the dashboards server.

https://github.com/jupyter-incubator/dashboards_server/blob/master/README.md

Congrats on bowtie, dashboarding is a gap in the ecosystem that needs more love!

**Comment by jwkvam** [comment]
I'll have to check that out, that looks very compelling if only for the fact that many people are already familiar with jupyter notebooks.

Thanks for the kind words though, appreciate it!
